# Generated by Django 5.1.5 on 2025-02-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='services', verbose_name='Imagen'),
        ),
    ]
