# Generated by Django 5.1.5 on 2025-01-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('filevideo', models.FileField(null=True, upload_to='media/videos/', verbose_name='Archivo de vídeo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de carga')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'db_table': 'Proyectos',
                'ordering': ['-created'],
            },
        ),
    ]
