# Generated by Django 5.1.5 on 2025-01-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='filevideo',
            field=models.FileField(null=True, upload_to='projects', verbose_name='Archivo de vídeo'),
        ),
    ]
